config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  
  get 'home/index'
  get 'posts/myposts'
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to posts_path, notice: "This post is managed by another user, you do not have the required permissions to manage this post" if @post.nil?
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:author, :title, :content, :image, :private, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1 class="title text-center mt-5 mb-3 important">What this website is all about</h1>

<p>This is a website for those who appreciate art to share the pieces they love. <strong>Any</strong> images that classify as art can be published here and shared with other users.
 This includes but is not limited to photography, paintaings, sculptures, etc. Be sure to include a title for the art piece, the author and any thoughts you want to add regarding the art  </p>

<h1 class="title text-center mt-5 mb-3 important">How to use this website</h1>

<p>To view content on the website simply go to the posts page in the header to view what others have posted. Scrolling through the posts page will only show you a condensed version of the post.
To view what the user has to say about the post and show a bigger version of the image, press the show button. You will only be able to see posts from users who haven't listed their 
posts privately. To create and manage your own posts, you must make an account and sign in to it. This enables you to create, edit, and delete your posts. Your posts will be highlighted blue in the posts page for clarity</p>

<h1 class="title text-center mt-5 mb-3 important">User System</h1>

<p>The login system allows you to sign up, log in, and cancel your account. If you forget your password, an email will be sent to help you. You can also edit your account after creating it if you wish to do so.</p>

<div class="text-center mt-5">
    <%= link_to 'Posts Page', posts_path, class: "btn btn-primary mb-3" %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info opacity-7">
  <div class="container-fluid">
    <%= link_to "Post Website", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to "Home Page", home_index_path, class:"nav-link" %>
        </li>
        
        <li class="nav-item">
                <%= link_to "Posts", posts_path, class:"nav-link" %>
        </li>

        <% if !user_signed_in? %>

            <li class="nav-item  float-end">
                <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
            </li>

            <li class="nav-item  float-end">
                <%= link_to "Sign in", new_user_session_path, class:"nav-link" %>
            </li>
        <% else %>
            
            <li class="nav-item">
                <%= link_to "New Post", new_post_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "Sign out",  destroy_user_session_path, method: :delete, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "Edit profile", edit_user_registration_path, class:"nav-link" %>
            </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <title>Image Repository</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header"%>
    <div class="container">
        <br>
        <% if notice %>
            <%=render "layouts/notice"%>
        <% end %>
        <%= yield %>
    </div>
    
  </body>

</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field input-group mb-3">
    <span class="input-group-text">Author</span>
    <%= form.text_field :author, required: "required", class: "form-control" %>
  </div>

  <div class="field input-group mb-3">
    <span class="input-group-text">Title</span>
    <%= form.text_field :title, required: "required", class: "form-control"  %>
  </div>

  <div class="field input-group mb-3">
    <span class="input-group-text">Content</span>
    <%= form.text_area :content, class: "form-control"  %>
  </div>

  <div class="field">
    <% if @post.image.attached? %>
          <%= image_tag post.image, style: "width;200px; display: block", class: "mb-3, showImage" %>
    <% end %>

    <%= form.label :image%>
    <%= form.file_field :image, class: "form-control mb-3", required: "required" %>
  </div>

  <div class="field form-check mb-3">
    <%= form.check_box :private, class: "form-check-input" %>
    <%= form.label :private, class: "form-check-label" %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, hidden: "hidden" %>
  </div>

  <div class="actions">
    <%= form.submit "Upload Post", class: "btn btn-success mb-3" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: "btn btn-info mb-3" %>
<%= link_to 'Back', posts_path, class: "btn btn-primary mb-3" %>

app/views/posts/index.html.erb
<h1 class="text-center">Public Post Feed</h1>

<div class="container w-50">
  <% @posts.each do |post| %>
    <% if !post.private or post.user == current_user %>
      <div class="p-3 mb-1 <%= 'currentUserPost' if post.user == current_user %>">
          <%= image_tag(post.image, class:"img-thumbnail")%>
          Author: <%= post.author %> |
          Title: <%= post.title %> |
          <%= link_to 'Show', post %>
          <% if post.user == current_user %> |
            <%= link_to 'Edit', edit_post_path(post) %> |
            <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      </div>
    <%end%>
  <%end%>
</div>
<br>

<div class="text-center mb-5">
  <%= link_to 'New Post', new_post_path, class: "btn btn-primary m-*-auto" %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: "btn btn-primary m-*-auto" %>

app/views/posts/show.html.erb
<p class="text-center title">
  <%= @post.title %>
<br>

<%= image_tag(@post.image, class: "showImage mt-2 mb-2")%>

</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<% if @post.user == current_user%>
  <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-success mb-3" %>
<%end%>
<%= link_to 'Back', posts_path, class: "btn btn-primary mb-3" %>